import type { Metadata } from "next";
import "./globals.css";
import { AntdNextRegistry } from "@/components/systeam/AntdNextRegistry";
import { useMemo } from "react";
import color from "color";
import { AppFuncInject } from "@/utils/appFunc";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const colorPrimary = "#278ED3";
  const style = useMemo(() => {
    return {
      "--color-primary-50": color(colorPrimary).lighten(0.8).hex(),
      "--color-primary-100": color(colorPrimary).lighten(0.6).hex(),
      "--color-primary-200": color(colorPrimary).lighten(0.5).hex(),
      "--color-primary-300": color(colorPrimary).lighten(0.4).hex(),
      "--color-primary-400": color(colorPrimary).lighten(0.2).hex(),
      "--color-primary-500": color(colorPrimary).lighten(0).hex(),
      "--color-primary-600": color(colorPrimary).darken(0.1).hex(),
      "--color-primary-700": color(colorPrimary).darken(0.2).hex(),
      "--color-primary-800": color(colorPrimary).darken(0.3).hex(),
      "--color-primary-900": color(colorPrimary).darken(0.4).hex(),
    };
  }, [colorPrimary]);

  return (
    <html lang="zh-CN">
      <body style={style as React.CSSProperties}>
        <AntdNextRegistry colorPrimary={colorPrimary}>
          <AppFuncInject />
          {children}
        </AntdNextRegistry>
      </body>
    </html>
  );
}
